services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    image: intervue:latest
    ports:
      - "3000:3000"
    env_file:
      - .env